In [1]:
#04数据操作＋数据预处理

In [28]:
import torch

In [3]:
#张量表示一个数值组成的数组，这个数组可能有多个维度

In [4]:
x=torch.arange(12)       #PyTorch 中，torch.arange 是一个用于生成连续整数张量的函数

In [5]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
#我们可以通过张量的shape属性来访问张量的形状和张量中元素的总数

In [7]:
x.shape   #x.shape 来获取张量 x 的形状（即维度和大小）,以下表示张量 x 的形状是一个长度为 12 的一维数组。

torch.Size([12])

In [14]:
x.numel() #x.numel() 来返回张量 x 中所有元素的总数  

12

In [15]:
#要改变一个张量的形状而不改变元素数量和元素值，可以调用reshape函数

In [23]:
X=x.reshape(3,4)

In [24]:
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [25]:
#使用全0、全1、其他常量或者从特定分布中随机采样的数字

In [27]:
torch.zeros((2,3,4)) #torch.zeros((2, 3, 4)) 会创建一个形状为 (2, 3, 4) 的三维张量，其中所有元素都为零。

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [29]:
torch.ones((2,3,4))  #形状 (2, 3, 4)：
                     #第一个维度（大小为 2）表示张量中有两个“块”。
                     #每个块是一个形状为 (3, 4) 的二维张量，表示 3 行 4 列。
                     #因此，整个张量是一个三维张量，包含 24 个零元素（2 × 3 × 4 = 24）。

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [ ]:
# 因此，整个张量是一个三维张量.
# 问题1：三行四列是否是二维
# 问题2：形状（3，4，4）是否是四维
# 问题3：形状（2，3，4）是否是由于有两个三行四列这两个二维才是三维，这种情况下形状（1，3，4）则为二维
# 问题4：形状（2，3，4）是否是由于三行四列中有三行，不论第一个数是2（张量中有两个块）还是多少，这种情况下形状（1，4，4）和形状（4，4，4）为四维
# 因此，整个张量是一个三维张量.问题1：三行四列是否是二维
# 问题2：形状（3，4，4）是否是四维
# 问题3：形状（2，3，4）是否是由于有两个三行四列这两个二维才是三维，这种情况下形状（1，3，4）则为二维
# 问题4：形状（2，3，4）是否是由于三行四列中有三行，不论第一个数是2（张量中有两个块）还是多少，这种情况下形状（1，4，4）和形状（4，4，4）为四维
# Avatar
# 你的问题涉及到张量的维度和形状的理解，这是一个非常重要的概念。我们来逐一解答你的问题：
# 问题1：三行四列是否是二维？
# 答案：是的。
# 一个“三行四列”的张量是一个二维张量（矩阵）。它的形状是 (3, 4)，表示它有 3 个行（第一维）和 4 个列（第二维）。
# 问题2：形状 (3, 4, 4) 是否是四维？
# 答案：不是，它是三维。
# 形状 (3, 4, 4) 表示张量有三个维度：
# 第一个维度大小为 3，表示有 3 个“块”。
# 每个块是一个形状为 (4, 4) 的二维矩阵（4 行 4 列）。
# 因此，整个张量是一个三维张量，而不是四维。
# 问题3：形状 (2, 3, 4) 是否是因为有两个三行四列的二维张量，所以是三维？
# 答案：是的。
# 形状 (2, 3, 4) 的张量可以理解为：
# 第一个维度大小为 2，表示有 2 个“块”。
# 每个块是一个形状为 (3, 4) 的二维矩阵（3 行 4 列）。
# 因此，整个张量是一个三维张量。
# 关于形状 (1, 3, 4) 是否为二维：
# 答案：不是。
# 形状 (1, 3, 4) 仍然是一个三维张量。虽然第一个维度的大小为 1，但它仍然表示一个“块”，而这个块是一个形状为 (3, 4) 的二维矩阵。
# 如果你希望将 (1, 3, 4) 转换为二维张量，可以使用 torch.squeeze() 方法，去掉大小为 1 的维度，得到形状为 (3, 4) 的二维张量。
# 问题4：形状 (2, 3, 4) 是否是因为三行四列中有三行，不论第一个数是 2 还是多少，这种情况下形状 (1, 4, 4) 和形状 (4, 4, 4) 都是四维？
# 答案：不是。
# 形状 (2, 3, 4) 是一个三维张量，因为：
# 第一个维度表示“块”的数量。
# 每个块是一个形状为 (3, 4) 的二维矩阵。
# 形状 (1, 4, 4)：
# 这仍然是一个三维张量。第一个维度大小为 1，表示有一个“块”，而这个块是一个形状为 (4, 4) 的二维矩阵。
# 形状 (4, 4, 4)：
# 这也是一个三维张量。第一个维度大小为 4，表示有 4 个“块”，每个块是一个形状为 (4, 4) 的二维矩阵。
# 四维张量的例子：
# 一个四维张量的形状可能是 (2, 3, 4, 5)，表示：
# 第一个维度大小为 2，表示有 2 个“组”。
# 每个组包含 3 个“块”。
# 每个块是一个形状为 (4, 5) 的二维矩阵。
# 总结：
# 张量的维度由其形状的长度决定：
# 形状 (3, 4) 是二维张量。
# 形状 (2, 3, 4) 是三维张量。
# 形状 (1, 3, 4) 也是三维张量。
# 形状 (4, 4, 4) 是三维张量。
# 形状 (2, 3, 4, 5) 是四维张量。
# 希望这些解释能帮助你更好地理解张量的维度和形状！

In [31]:
#通过提供包含数值的Python列表（或嵌套列表）来为所需张量中的每个元素赋予确定值

In [33]:
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])  #tensor：张量

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [47]:
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]]).shape #行是一个维度，列是一个维度，形状是三行四列

torch.Size([3, 4])

In [49]:
torch.tensor([[[2,1,4,3],[1,2,3,4],[4,3,2,1]]]).shape #加一对中括号，升一个维度，整体为一个块

torch.Size([1, 3, 4])

In [51]:
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]]).numel()  #三行四列共12个元素

12

In [53]:
#常见的标准算数运算符（+、-、*、/和**）都可以被升级为按元素运算

In [61]:
x=torch.tensor([1.0,2,4,8])
y=torch.tensor([2,2,2,2])
x+y,x-y,x*y,x/y,x**y #**运算符是求幂运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [63]:
#更多的运算

In [65]:
torch.exp(x)   #指数运算,e的x次方

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [67]:
#我们也可以把多个张量连结在一起

In [27]:
X=torch.arange(12,dtype=torch.float32).reshape((3,4))
Y=torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=1)     #dim=0是第0维合并，按行合并，增加行

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [12]:
#通过逻辑运算符构建二元张量

In [29]:
X==Y     #判断Y是不是等于X，按每个元素值判

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [13]:
#对张量中的所有元素进行求和会产生一个只有一个元素的张量

In [30]:
X.sum(),Y.sum()

(tensor(66.), tensor(30.))

In [17]:
#即使形状不同(但维度一样)，我们仍然可以通过调用 广播机制（broadcasting mechanism）来执行按元素操作

In [31]:
a=torch.arange(3).reshape((3,1))
b=torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [32]:
a+b     #广播机制化为相同形式（3*2+3*2）；类似线性代数中 3*1  1*2  结果  3*2

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [25]:
#读取：可以用[-1]选择最后一个元素，可以用[1:3]选择第二个和第三个元素

In [33]:
X[-1],X[1:3],X[-1,1:2]    #前面已经提到了

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([9.]))

In [31]:
#写入矩阵：单个赋值，通过指定索引来将元素写入矩阵

In [35]:
X[1,2]=9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [37]:
#写入矩阵：区域赋值，为多个元素赋值相同的值，我们只需要索引所有元素，然后为它们赋值

In [39]:
X[0:2,:]=12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [42]:
#运行一些操作可能会导致为新结果分配内存（大内存的地方不要过多赋值）

In [37]:
id(X),id(Y)

(2041538180976, 2041538136640)

In [44]:
before=id(Y)  #id() 函数用于获取一个对象的内存地址（即对象的唯一标识）
Y=Y+X   #显式赋值
id(Y)==before

False

In [48]:
id(Y),before

(2041538136640, 2041538136640)

In [47]:
before=id(Y)  #id() 函数用于获取一个对象的内存地址（即对象的唯一标识）
Y+=X   #增强赋值,X的值加进Y里面
id(Y)==before

True

In [50]:
#执行原地操作

In [45]:
z=torch.zeros_like(Y)
print('id(z):',id(z))
z[:]=X+Y
print('id(z):',id(z))

id(z): 2041538181536
id(z): 2041538181536


In [76]:
#如果在后续计算中没有重复使用X，我们也可以使用X[:]=X+Y或X+=Y来减少操作的内存开销

In [78]:
before=id(X)    #前面已提到
X+=Y
id(X)==before

True

In [80]:
#torch张量转换为numpy类型，再拿回来

In [86]:
X

tensor([[50., 49., 52., 51.],
        [49., 50., 51., 52.],
        [36., 39., 42., 45.]])

In [96]:
A=X.numpy()
A

array([[50., 49., 52., 51.],
       [49., 50., 51., 52.],
       [36., 39., 42., 45.]], dtype=float32)

In [98]:
B=torch.tensor(A)
B

tensor([[50., 49., 52., 51.],
        [49., 50., 51., 52.],
        [36., 39., 42., 45.]])

In [100]:
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [102]:
#将大小为1的张量转化为Python标量（将张量tensor里元素提出来）

In [14]:
a=torch.tensor([3.5])
a,a.item(),float(a),int(a)     #item() 方法将一个只有一个元素的张量转换为 Python 的标量（原生数值类型）
#float() 和 int() 不能直接作用于整个张量。它们只能用于单个元素的张量。
#如果只想提取张量中的某个特定元素并进行类型转换，可以通过索引操作来实现
#如果需要将多元素张量转换为 Python 列表，可以使用 .tolist() 方法

(tensor([3.5000]), 3.5, 3.5, 3)

In [ ]:
##数据预处理（创建读取csv文件，做特征预处理，变成pytorch用的张量形式）

In [ ]:
#创建一个人工数据集，并存储在csv（逗号分割值）文件

In [5]:
import os   #（os创建文件）
os.makedirs(os.path.join('..','data'),exist_ok=True) 
#在当前工作目录的上一级目录中创建一个名为 data 的文件夹。如果该文件夹已经存在，不会报错
data_file=os.path.join('..','data','house_tiny.csv')  #文件夹下创建csv文件的路径，不是文件本身，此时没有实际创建
#（csv:每一行代表一条记录,每条记录由多个字段组成，字段之间用逗号（,）分隔。可选地，字段可以用双引号（"）括起来，以支持字段中包含逗号或换行符的情况）
with open(data_file,'w') as f:
    f.write('NumRooms,Alley,Price\n')  #列名
    f.write('NA,Pave,127000\n')  #，每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,141000\n')

In [6]:
# os.path.join('..', 'data')
# os.path.join 是一个用于路径拼接的函数，它会根据操作系统（如 Windows 使用 \，Linux/Unix 使用 /）自动选择正确的路径分隔符。
# '..' 表示当前目录的上一级目录。一个点是本级目录
# 'data' 是要创建的目录名称。
# 因此，os.path.join('..', 'data') 会生成一个路径，指向当前目录的上一级目录中的 data 文件夹。
# 例如：
# 如果当前工作目录是 /home/user/project，那么生成的路径将是 /home/user/data。
# 如果当前工作目录是 C:\project，那么生成的路径将是 C:\data。
# os.makedirs
# os.makedirs 是一个用于创建多级目录的函数。它会创建目标路径中所有不存在的目录。
# 参数 exist_ok=True 表示如果目标目录已经存在，不会抛出错误。如果没有设置 exist_ok=True，当目标目录已经存在时，os.makedirs 会抛出 FileExistsError。
# 完整代码的作用:
# 这行代码的作用是：
# 在当前工作目录的上一级目录中创建一个名为 data 的文件夹。
# 如果该文件夹已经存在，不会报错（因为设置了 exist_ok=True）。

In [7]:
# 1. 为什么是 with open？
# with open 是 Python 中的一个上下文管理器（context manager），用于自动管理文件的打开和关闭。使用 with open 有几个好处：
# 自动关闭文件：无论文件操作过程中发生什么（包括异常），文件都会在 with 块结束时自动关闭，这有助于防止文件泄露。
# 简化代码：不需要显式调用 close() 方法来关闭文件。
# 提高安全性：减少因忘记关闭文件而造成的资源泄露风险。
# 2. 为什么是 'w'？
# 在 open 函数中，'w' 是一个模式参数，表示以写入模式打开文件。这个模式的作用如下：
# 写入模式：如果文件已存在，它会被覆盖。如果文件不存在，会创建一个新文件。
# 其他模式：除了 'w'，还有其他模式如 'r'（只读，文件必须存在），'a'（追加，如果文件存在则在末尾添加内容，不存在则创建新文件），'r+'（读写，文件必须存在）等。
# 3. 为什么是 as f？
# as f 是将 open 函数返回的文件对象赋值给变量 f。这样做的好处是：
# 方便引用：在 with 块内部，您可以使用变量 f 来引用文件对象，进行读写操作。
# 提高可读性：使用有意义的变量名（如 f 代表文件）可以使代码更易于理解和维护。

In [8]:
#从创建的csv文件中加载原始数据集(pandas读文件)

In [9]:
import pandas as pd

data=pd.read_csv(data_file) #pandas提供的read_csv函数
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127000
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  141000


In [10]:
data #不用print，直接data，是HTML形式，更紧凑

NumRooms Alley   Price
0       NaN  Pave  127000
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  141000

In [11]:
#为了处理缺失的培训，典型的方法包括插值和删除，这里考虑插值

In [12]:
inputs,outputs=data.iloc[:,0:2],data.iloc[:,2] #每行分成输入和输出，iloc:index location
inputs=inputs.fillna(inputs.mean(numeric_only=True))#fillna函数有调整，需加numeric_only=True，只考虑数值列
#.mean()是平均值mean,如inputs=d.iloc[:,0]   inputs.mean()
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [84]:
# iloc 是 pandas 中用于基于整数位置的索引方法。它允许你通过行号和列号选择数据。
# iloc 的语法是 data.iloc[行索引, 列索引]，其中行索引和列索引可以是整数、切片（:）、列表或布尔数组。
#integer location

In [86]:
#对于Inputs中的类别值或离散值，我们将“NAN”视为一个类别

In [16]:
inputs=pd.get_dummies(inputs,dummy_na=True,dtype=float)
print(inputs)
#torch 2.0会默认使用True和False，替换原来的0和1，后续可能报错。可以增加一个属性到get_dummies中：dtype=float
# pd.get_dummies：Pandas 提供的用于对数据进行独热编码（One-Hot Encoding）的函数。
# dummy_na=True：将缺失值（NA）视为一个单独的类别进行编码。(取得笨蛋)
# dtype=float：将生成的独热编码列的数据类型设置为浮点型。

   NumRooms  Alley_Pave  Alley_nan
0       3.0         1.0        0.0
1       2.0         0.0        1.0
2       4.0         0.0        1.0
3       3.0         0.0        1.0


In [15]:
outputs

0    127000
1    106000
2    178100
3    141000
Name: Price, dtype: int64

In [13]:
#现在inputs和outpouts中的所有条目都是数值类型，它们可以转换为张量格式

In [17]:
import torch

X,y=torch.tensor(inputs.values),torch.tensor(outputs.values)
X,y
#inputs.values 和 outputs.values：
# inputs 和 outputs 分别是 Pandas DataFrame 和 Series。
# inputs.values 和 outputs.values 将 DataFrame 和 Series 转换为 NumPy 数组。
# 这些 NumPy 数组随后被传递给 torch.tensor，以创建 PyTorch 张量。
# X, y：
# X 是输入特征的张量，通常用于模型的输入。
# y 是目标值（标签）的张量，通常用于模型的输出或监督学习中的目标。
#传统python默认float64,计算比较慢，对深度学习来讲通常用32位浮点数，后面会讲到

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127000, 106000, 178100, 141000]))