In [ ]:
#05 线性代数

In [ ]:
#标量由只有一个元素的张量表示

In [5]:
import torch
x=torch.tensor([3.0])  
y=torch.tensor([2.0])
x+y,x*y,x/y,x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [ ]:
#创建向量：向量是由标量值组成的列表

In [5]:
x=torch.arange(4)
x

tensor([0, 1, 2, 3])

In [ ]:
#通过张量的索引来访问向量的任一元素

In [6]:
x[3]

tensor(3)

In [ ]:
#访问张量的长度

In [7]:
len(x)

4

In [ ]:
#只有一个轴的张量，形状只有一个元素

In [8]:
x.shape

torch.Size([4])

In [ ]:
#创建矩阵：指定两个分量m和n来创建一个形状为m*n的矩阵

In [9]:
A=torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [ ]:
#矩阵的转置：

In [10]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [ ]:
#对称矩阵A等于其转置   A=A^T  (对称轴i=j上任意)

In [13]:
B=torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [14]:
B==B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [ ]:
#就像标量推向量，向量推矩阵一样，可以构建具有更多轴的数据结构

In [15]:
X=torch.arange(24).reshape(2,3,4)  #注意(24=2*3*4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [ ]:
#给定具有形同形状的任何两个张量，任何按元素二元运算的结果都将是相同形状的张量

In [17]:
A=torch.arange(20,dtype=torch.float32).reshape(5,4)
B=A.clone() #通过分配新内存，将A的一个副本分配给B(前面讲过B=A,这个不会分配新内存)
A,A+B,A+B+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]),
 tensor([[ 0.,  3.,  6.,  9.],
         [12., 15., 18., 21.],
         [24., 27., 30., 33.],
         [36., 39., 42., 45.],
         [48., 51., 54., 57.]]))

In [ ]:
#两个矩阵的按元素乘法称为 哈达玛积

In [18]:
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [ ]:
#前面讲过标量和矩阵的运算：标量加入矩阵，标量乘以矩阵

In [30]:
a=2                            #标量，与a=torch.tensor([2])效果一样
X=torch.arange(24).reshape(2,3,4)
X,a+X,a-x,x-a,a*x,(a*X).shape #除加法外，其它的打印不全，可以设置打印选项torch.set_printoptions(threshold=10000)

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 tensor([ 2,  1,  0, -1]),
 tensor([-2, -1,  0,  1]),
 tensor([0, 2, 4, 6]),
 torch.Size([2, 3, 4]))

In [8]:
a=2                           
X=torch.arange(24).reshape(2,3,4)
torch.set_printoptions(threshold=10000)
a-X

tensor([[[  2,   1,   0,  -1],
         [ -2,  -3,  -4,  -5],
         [ -6,  -7,  -8,  -9]],

        [[-10, -11, -12, -13],
         [-14, -15, -16, -17],
         [-18, -19, -20, -21]]])

In [23]:
a=torch.tensor([2])
X=torch.arange(24).reshape(2,3,4)
X,a+X,a-x,x-a,a*x,(a*X).shape 

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 tensor([ 2,  1,  0, -1]),
 tensor([-2, -1,  0,  1]),
 tensor([0, 2, 4, 6]),
 torch.Size([2, 3, 4]))

In [ ]:
#计算sum元素和

In [33]:
x=torch.arange(4,dtype=torch.float32)
x,x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [ ]:
#任意张量的形状和元素和

In [39]:
A=torch.arange(20,dtype=torch.float32).reshape(5,4)
A.shape,A.sum()

(torch.Size([5, 4]), tensor(190.))

In [37]:
A=torch.arange(20*2,dtype=torch.float32).reshape(2,5,4)
A,A.shape,A.sum()

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]),
 torch.Size([2, 5, 4]),
 tensor(780.))

In [45]:
A=torch.arange(20*2,dtype=torch.float32).reshape(2,5,4)
A_sum_axis0=A.sum(axis=0)       #按‘2’这个维度求和，‘2’没有了，剩下维度为5*4
A,A_sum_axis0,A_sum_axis0.shape  #axis,英语翻译为轴

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]),
 tensor([[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]]),
 torch.Size([5, 4]))

In [47]:
A=torch.arange(20*2,dtype=torch.float32).reshape(2,5,4)
A_sum_axis0=A.sum(axis=1)       #按‘5’这个维度求和，‘5’没有了（行没有了，对应列相加），剩下维度为2*4
A,A_sum_axis0,A_sum_axis0.shape

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]),
 tensor([[ 40.,  45.,  50.,  55.],
         [140., 145., 150., 155.]]),
 torch.Size([2, 4]))

In [48]:
A=torch.arange(20*2,dtype=torch.float32).reshape(2,5,4)
A_sum_axis0=A.sum(axis=2)       #按‘4’这个维度求和，‘4’没有了（列没有了，对应行相加），剩下维度为2*5
A,A_sum_axis0,A_sum_axis0.shape

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]),
 tensor([[  6.,  22.,  38.,  54.,  70.],
         [ 86., 102., 118., 134., 150.]]),
 torch.Size([2, 5]))

In [51]:
A=torch.arange(20*2,dtype=torch.float32).reshape(2,5,4)
A_sum_axis0=A.sum(axis=[0,1])   #按‘2’和‘5’这两个维度求和，剩下维度为4（4列）
A,A_sum_axis0,A_sum_axis0.shape #3+7+11+15+19+23+27+31+35+39=210

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]),
 tensor([180., 190., 200., 210.]),
 torch.Size([4]))

In [52]:
A=torch.arange(20*2,dtype=torch.float32).reshape(2,5,4)
A_sum_axis0=A.sum(axis=[0,2])   #按‘2’和‘4’这两个维度求和，剩下维度为5（5行）
A,A_sum_axis0,A_sum_axis0.shape  #16+17+18+19+36+37+38+39=220

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]),
 tensor([ 92., 124., 156., 188., 220.]),
 torch.Size([5]))

In [53]:
#任意张量的平均值(mean或average)

In [56]:
A=torch.arange(20*2,dtype=torch.float32).reshape(2,5,4)
A,A.mean(),A.sum()/A.numel()

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]),
 tensor(19.5000),
 tensor(19.5000))

In [ ]:
#按某个维度来算均值

In [65]:
A=torch.arange(20*2,dtype=torch.float32).reshape(2,5,4)
A,A.mean(axis=0),A.sum(axis=0)/A.shape[0],A.shape[0]#按‘2’这个维度求均值，剩下5*4，均值各元素除以2（shape[0]）
#(19+39)/2=29

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]),
 tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]),
 tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]),
 2)

In [66]:
A=torch.arange(20*2,dtype=torch.float32).reshape(2,5,4)
A,A.mean(axis=1),A.sum(axis=1)/A.shape[1],A.shape[1]#按‘5’这个维度求均值，剩下2*4，均值各元素除以5（shape[1]）
#(23+27+31+35+39)/5=31

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]),
 tensor([[ 8.,  9., 10., 11.],
         [28., 29., 30., 31.]]),
 tensor([[ 8.,  9., 10., 11.],
         [28., 29., 30., 31.]]),
 2)

In [ ]:
#按维度求和会丢掉维度，想要保留的话加 keepdims=True   dims是单词dimession维度

In [6]:
A=torch.arange(20*2,dtype=torch.float32).reshape(2,5,4)
A_sum_axis0=A.sum(axis=1)       #按‘5’这个维度求和，‘5’没有了（行没有了，对应列相加），剩下维度为2*4
A,A_sum_axis0,A_sum_axis0.shape

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]),
 tensor([[ 40.,  45.,  50.,  55.],
         [140., 145., 150., 155.]]),
 torch.Size([2, 4]))

In [7]:
sum_A=A.sum(axis=1,keepdims=True)#这样保留了维度，好处是可以通过广播机制将A除以sum_A
sum_A,sum_A.shape  #23+27+31+35+39=155       #保留的维度为1 [2,5,4]变为[2,1,4]

(tensor([[[ 40.,  45.,  50.,  55.]],
 
         [[140., 145., 150., 155.]]]),
 torch.Size([2, 1, 4]))

In [72]:
A/sum_A #23/155=0.1484
        #27/155=0.1742

tensor([[[0.0000, 0.0222, 0.0400, 0.0545],
         [0.1000, 0.1111, 0.1200, 0.1273],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.3000, 0.2889, 0.2800, 0.2727],
         [0.4000, 0.3778, 0.3600, 0.3455]],

        [[0.1429, 0.1448, 0.1467, 0.1484],
         [0.1714, 0.1724, 0.1733, 0.1742],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.2286, 0.2276, 0.2267, 0.2258],
         [0.2571, 0.2552, 0.2533, 0.2516]]])

In [79]:
#某个轴计算A元素的累计总和
A,A.sum(axis=0),A.cumsum(axis=0) #16+36=52,17+37=54,18+38=56,19+39=58
#后一个块为前面所有块对应相加

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]),
 tensor([[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]]),
 tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 22., 24., 26.],
          [28., 30., 32., 34.],
          [36., 38., 40., 42.],
          [44., 46., 48., 50.],
          [52., 54., 56., 58.]]]))

In [77]:
#某个轴计算A元素的累计总和
A,A.sum(axis=1),A.cumsum(axis=1) #下一行为上面所有行相加 
                                # + 20 21 22 23 
                                # + 24 25 26 27
                                #=  44 46  48  50

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]),
 tensor([[ 40.,  45.,  50.,  55.],
         [140., 145., 150., 155.]]),
 tensor([[[  0.,   1.,   2.,   3.],
          [  4.,   6.,   8.,  10.],
          [ 12.,  15.,  18.,  21.],
          [ 24.,  28.,  32.,  36.],
          [ 40.,  45.,  50.,  55.]],
 
         [[ 20.,  21.,  22.,  23.],
          [ 44.,  46.,  48.,  50.],
          [ 72.,  75.,  78.,  81.],
          [104., 108., 112., 116.],
          [140., 145., 150., 155.]]]))

In [78]:
#某个轴计算A元素的累计总和(cumulation)
A,A.sum(axis=2),A.cumsum(axis=2) #后一列为前面所有列相加

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]),
 tensor([[  6.,  22.,  38.,  54.,  70.],
         [ 86., 102., 118., 134., 150.]]),
 tensor([[[  0.,   1.,   3.,   6.],
          [  4.,   9.,  15.,  22.],
          [  8.,  17.,  27.,  38.],
          [ 12.,  25.,  39.,  54.],
          [ 16.,  33.,  51.,  70.]],
 
         [[ 20.,  41.,  63.,  86.],
          [ 24.,  49.,  75., 102.],
          [ 28.,  57.,  87., 118.],
          [ 32.,  65.,  99., 134.],
          [ 36.,  73., 111., 150.]]]))

In [80]:
#向量的点积：点积是相同位置的按元素乘积的和(点积是和，区别前面矩阵的哈达玛积)

In [81]:
y=torch.ones(4,dtype=torch.float32)
x,y,torch.dot(x,y)   #dot翻译为 点

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [83]:
#点积等价于哈达玛积再求和
x*y,torch.sum(x*y)

(tensor([0., 1., 2., 3.]), tensor(6.))

In [ ]:
#矩阵与向量的积Ax是一个长度为m的列向量（A:m*n,x:n*1,Ax:m*1）

In [88]:
A=torch.arange(20,dtype=torch.float32).reshape(5,4)
A,x,A.shape,x.shape,torch.mv(A,x)    #matrix-vector,矩阵向量积

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([0., 1., 2., 3.]),
 torch.Size([5, 4]),
 torch.Size([4]),
 tensor([ 14.,  38.,  62.,  86., 110.]))

In [ ]:
#矩阵向量积拓展为矩阵-矩阵积：矩阵-矩阵乘法AB看作m次矩阵-向量积，结果拼接到一起

In [91]:
B=torch.ones(4,3)
A,B,torch.mm(A,B)    #matrix-matrix ，矩阵-矩阵乘积

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[ 6.,  6.,  6.],
         [22., 22., 22.],
         [38., 38., 38.],
         [54., 54., 54.],
         [70., 70., 70.]]))

In [ ]:
#L2范数是向量元素平方和的平方根（类似勾股定理）

In [92]:
u=torch.tensor([3.0,-4.0])
torch.norm(u)     #norm，常态，规范，范数

tensor(5.)

In [ ]:
#L1范数是向量元素的绝对值之和

In [93]:
torch.abs(u).sum()  #abs,absolute value，绝对的值

tensor(7.)

In [ ]:
#F范数是矩阵元素的平方和的平方根(等价于把矩阵拉成向量来求范数)

In [95]:
torch.ones((4,9))

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [94]:
torch.norm(torch.ones((4,9))) #根号36

tensor(6.)