In [1]:
import torch

In [6]:
a=torch.arange(3).reshape((3,1))
b=torch.arange(2).reshape((1,2))
a,b,a+b,a-b,a*b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]),
 tensor([[0, 1],
         [1, 2],
         [2, 3]]),
 tensor([[ 0, -1],
         [ 1,  0],
         [ 2,  1]]),
 tensor([[0, 0],
         [0, 1],
         [0, 2]]))

In [7]:
X=torch.arange(12,dtype=torch.float32).reshape((3,4))
X[-1],X[1:3],X[-1,1:2]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([9.]))

In [10]:
X[1,2]=9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [11]:
X[0:2,:]=12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [12]:
Y=torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])

In [15]:
z=torch.zeros_like(X)
print('id(z):',id(z))
z[:]=X+Y
print('id(z):',id(z))

id(z): 2062217598032
id(z): 2062217598032


In [16]:
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [18]:
A=X.numpy()
A

array([[12., 12., 12., 12.],
       [12., 12., 12., 12.],
       [ 8.,  9., 10., 11.]], dtype=float32)

In [20]:
B=torch.tensor(A)
B

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [21]:
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [2]:
import sys
print(sys.executable)

D:\Anaconda\envs\d2l-zh\python.exe


In [7]:
#04-3 数据预处理
import os
os.makedirs(os.path.join('..','data1'),exist_ok=True)
data_file=os.path.join('..','data1','house.csv')
with open(data_file,'w') as f:
    f.write('NumRooms,Alley,Price\n')
    f.write('NA,Pave,127500\n')
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [13]:
#改动一下
import os
os.makedirs(os.path.join('.','data1'),exist_ok=True)
data_file=os.path.join('.','data1','house.csv')
with open(data_file,'w') as a:
    a.write('NumRooms,Alley,Price\n')
    a.write('NA,Pave,127500\n')
    a.write('2,NA,106000\n')
    a.write('4,NA,178100\n')
    a.write('NA,NA,140000\n')
    

In [14]:
import pandas as pd

data=pd.read_csv(data_file) #pandas提供的read_csv函数
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [16]:
import pandas as pd

d=pd.read_csv(data_file) #pandas提供的read_csv函数
d

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [17]:
inputs=d.iloc[:,0]
inputs.mean()

3.0

In [19]:
inputs,outpouts=d.iloc[:,0:2],d.iloc[:,2]
inputs=inputs.fillna(inputs.mean(numeric_only=True))
inputs

NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN

In [26]:
inputs=pd.get_dummies(inputs,dummy_na=True)
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0         1.0        0.0
1       2.0         0.0        1.0
2       4.0         0.0        1.0
3       3.0         0.0        1.0


In [24]:
#05 线性代数
import torch 
x=torch.tensor([3.0])
y=torch.tensor([2.0])
x+y,x*y,x/y,x**y

x=torch.arange(4)
x[3],len(x),x.shape

A=torch.arange(20).reshape(5,4)
A.T
B=torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B==B.T

X=torch.arange(24).reshape(2,3,4)
X
A=torch.arange(20,dtype=torch.float32).reshape(5,4)
B=A.clone()
A,A+B,A+B+B,A*B,2*A,2+A,2-A

A=torch.arange(20*2,dtype=torch.float32).reshape(2,5,4)
A,A.shape,A.sum()
A_sum_axis0=A.sum(axis=[0,1])
A,A_sum_axis0,A_sum_axis0.shape
sum_A=A.sum(axis=1,keepdims=True)
sum_A
A,A.sum(axis=0),A.cumsum(axis=0)

x=torch.arange(4,dtype=torch.float32)
y=torch.ones(4,dtype=torch.float32)
x,y,torch.dot(x,y),torch.sum(x*y)

u=torch.tensor([3.0,-4.0])
torch.norm(u)
torch.abs(u).sum()
torch.norm(torch.ones((4,9)))

tensor(6.)